# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d4661d6a2d3c5ec8a105d34a349f0aac32c50658b3992d23269fcf908c6671acb3ccf3ea5f87200d24be3d0a64cf47d294786ef88aea326df3ba44cf68a87f0

test:
  secret_key_base: 52766b53db16dbdad8d4c1dd73b8fd008cab66100bbb90a8ae3d05fa0c4959e3e95c8c771a1b4d77981f200ac5901e820a274767dd8eb62bc5423400b5b42904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
